### ISSUE TITLE
Nueva versión del borrador

### ISSUE THREAD

**Issue by lfalvarez** [fguinez/nueva-constitucion#2]
Oye una pregunta, se están actualizando los artículos cacha que van en la [versión 3.0](https://www.duna.cl/noticias/2022/06/15/borrador-3-0-revisa-los-387-articulos-de-la-nueva-constitucion/), los tienes actualizados? necesitas ayuda actualizandolos?

**Comment by fguinez** [comment]
No estoy actualizando las versiones del borrador porque en estas cambia el orden y el número de artículos, entonces en la práctica no vale la pena cambiar los posts de twitter porque quedaría todo desordenado.

La fecha de entrega del texto final coincide con el término de los posts de primer borrador, entonces ahí si actualizaré el texto a la versión definitiva.

**Comment by lfalvarez** [comment]
buena bacán! Si se te ocurren ideas nuevas para el bot podrías ponerlas acá como issues para ver si te puedo dar una manito a veces.

**Comment by fguinez** [comment]
> buena bacán! Si se te ocurren ideas nuevas para el bot podrías ponerlas acá como issues para ver si te puedo dar una manito a veces.

Tienes razón! Creé las issues #3, #4 y #5 con las tareas que tenía pendientes de momento. En específico, las primeras se refieren a la posibilidad de implementar esta misma herramienta tanto en Facebook como en Instagram.
