### ISSUE TITLE
No es la propuesta final

### ISSUE THREAD

**Issue by fglaria** [fguinez/nueva-constitucion#6]
Revisando el contenido publicado, noto que no es la versión final del texto.
Creo que, dada la confusión y las campañas desinformativas, es urgente actualizar el articulado al definitivo.

**Comment by fguinez** [comment]
No entiendo bien a qué te refieres.

La propuesta final está subida como [`nueva_constitución_texto_definitivo.txt`](https://github.com/fguinez/nueva-constitucion/blob/main/nueva_constitución_texto_definitivo.txt)

Si revisas [`main.py`](https://github.com/fguinez/nueva-constitucion/blob/main/main.py), se hace referencia a este archivo:
```
filename = "nueva_constitución_texto_definitivo.txt"
```

Por lo que si se está publicando el texto original (puedes corroborarlo en [@nuevaconstCL](https://twitter.com/nuevaconstCL))

Ahora, si encontraste algún error en la transcripción a texto plano, te agradecería me indicaras la línea dentro de [`nueva_constitución_texto_definitivo.txt`](https://github.com/fguinez/nueva-constitucion/blob/main/nueva_constitución_texto_definitivo.txt) o al menos el artículo con problemas para poder solucionarlo a la brevedad.

Saludos✌️

**Comment by fglaria** [comment]
a que bruto de mi parte, como están al final de los archivos listados no la vi y me fijé en los borradores

**Comment by fguinez** [comment]
Aaah entiendo jaja, creo que igual dejaré el borrador dentro de una carpeta `versiones preliminares` o algo por el estilo para que quede más claro.

**Comment by fglaria** [comment]
A claro, con eso nadie se confundirá.
Si no te molesta, puse este repositorio en uno que cree para recopilarlos y ofrecer distintos formatos.
https://github.com/fglaria/propuesta_constitucion_chile_2022
Si prefieres no estar listado, lo saco.
